language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
cache: pip
install:
  - pip install -r dev-requirements.txt
script:
  - py.test --cov=./
after_success:
  - codecov
branches:
  only:
    - master